sequences: '/scicore/home/neher/kuznet0001/hiv_analysis/data/hiv-db.fasta'
metadata: "data/metadata.tsv"
nextclade_dataset_path: "community/neherlab/hiv-1/hxb2"
reference: "data/ref.fasta"
reference_ann: "/scicore/home/neher/kuznet0001/hiv_analysis/hiv_pipeline/data/genome_annotation.gff3"
auspice_config: "data/auspice_config.json"
tree_method: "fasttree"
# 'fasttree' or 'iqtree'
tree_args: ""
# --tree-builder-args '-m GTR+I+R10 -ninit 10 -n 4 -czb'
subset_n: 0 # 0 means no subsampling
threads: 32
cds: ["pol"]
results_dir: "results_051125"
auspice_dir: "auspice_051125"
